
version: "3.9"

# This name and resource names (networks/volumes) will be prefixed by COMPOSE_PROJECT_NAME from env file
name: ${COMPOSE_PROJECT_NAME:-dbanking-op1}

networks:
  op_net:
    name: ${COMPOSE_PROJECT_NAME}_net
    driver: bridge

volumes:
  op_postgres_data:
  op_rabbitmq_data:
  op_rabbitmq_log:

services:
  postgres:
    image: postgres:16
    container_name: ${COMPOSE_PROJECT_NAME}_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - op_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h localhost"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - op_net

  rabbitmq:
    image: rabbitmq:4.2.2-management
    container_name: ${COMPOSE_PROJECT_NAME}_rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "${RABBITMQ_AMQP_PORT}:5672"
      - "${RABBITMQ_HTTP_PORT}:15672"
    volumes:
      - op_rabbitmq_data:/var/lib/rabbitmq/mnesia
      - op_rabbitmq_log:/var/log/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - op_net

  customer_onboarding_api:
    build:
      context: ./dBanking.CustomerOnboarding.API
      dockerfile: Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME}_api
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}

      # Postgres envs consumed by Program.cs
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      PG_INCLUDE_ERROR_DETAIL: ${PG_INCLUDE_ERROR_DETAIL}

      # RabbitMQ envs consumed by Program.cs
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: "5672"
      RABBITMQ_VHOST: /
      RABBITMQ_USERNAME: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_USE_TLS: "false"
    ports:
      - "${API_HTTP_PORT}:9090"      # host:container
    networks:
      - op_net
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8080/health || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10
